# Generated by Django 4.2.7 on 2023-11-29 15:17

from django.db import migrations, models

import encrypted_files.fields
import encrypted_files.storage


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Foobar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "foo",
                    encrypted_files.fields.EncryptedFileField(
                        storage=encrypted_files.storage.EncryptedFileStorage(),
                        upload_to="somewhere/",
                    ),
                ),
            ],
        ),
    ]
